CDPython/social_media-main/social_media-main/core/urls.py
from django.urls import path
from core.views import index, JoinGroupView, LeaveGroupView, ManageGroupMembershipView,ListPendingMembershipsView, ConfirmMembershipView, delete_post, ForgotPasswordView
from core import views

app_name = "core"

urlpatterns = [
    path("",index, name="feed"),
    path("post/<slug:slug>/", views.post_detail, name="post-detail"),

    path("create-post/", views.create_post, name="create-post"),
    path("like-post/", views.like_post, name="like-post"),
    path("comment-post/", views.comment_on_post, name="comment-post"),
    path("like-comment/", views.like_comment, name="like-comment"),
    path("reply-comment/", views.reply_comment, name="reply-comment"),
    path("delete-comment/", views.delete_comment, name="delete-comment"),
    path('delete_post/', views.delete_post, name='delete_post'),
    path("add-friend/", views.add_friend, name="add-friend"),
    path("accept-friend-request/", views.accept_friend_request, name="accept-friend-request"),
    path("reject-friend-request/", views.reject_friend_request, name="reject-friend-request"),
    path("unfriend/", views.unfriend, name="unfriend"),
    path('delete-reply/', views.delete_reply, name='delete-reply'),
    path("like-page/", views.like_page, name="like-page"),
    path('edit-comment/', views.edit_comment, name='edit_comment'),
    path('delete_post/<slug:slug>/', views.delete_post, name='delete_post'),
    path('update_post/<slug:slug>/', views.update_post, name='update_post'),
    path('edit-reply/', views.edit_reply, name='edit_reply'),
    path('unblock_user/<int:user_id>/', views.unblock_user, name='unblock_user'),

    path('group/<int:group_id>/post-list/', views.group_post_list, name='group_post_list'),
    path('group/<int:group_id>/create-post/', views.create_group_post, name='create_group_post'),
    path('create-group/', views.create_group, name='create-group'),
    path("group-page/<id>/",views.group_index, name="group-page"),
    path('join-group/<int:group_id>/', JoinGroupView.as_view(), name='join-group'),
    path('leave-group/<int:group_id>/', LeaveGroupView.as_view(), name='leave-group'),
    path('manage-membership/<int:group_id>/<int:user_id>/<str:action>/', ManageGroupMembershipView.as_view(), name='manage-membership'),
    path('pending-memberships/<int:group_id>/', ListPendingMembershipsView.as_view(), name='pending-memberships'),
    path('confirm-membership/<int:user_id>/<str:action>/<int:group_id>/', ConfirmMembershipView.as_view(), name='confirm-membership'),
    path('delete_group/<int:group_id>/', views.delete_group, name='delete_group'),
    path('update_group/<int:group_id>/', views.update_group, name='update_group'),
    path('follow_user/<str:username>/', views.follow_user, name='follow_user'),
    path('groups/<int:group_id>/leave/', LeaveGroupView.as_view(), name='leave-group'),
    path('update_group_post/<int:group_id>/', views.update_group_post, name='update_group_post'),
    path('delete_group_post/<int:group_id>/', views.delete_group_post, name='delete_group_post'),
    path('list_groups/', views.list_groups, name='list_groups'),
     path('list_non_friends/', views.list_non_friends, name='list_non_friends'),

    path('page/<int:page_id>/post-list/', views.page_post_list, name='page_post_list'),
    #path('page/<int:page_id>/create-post/', views.create_page_post, name='create_page_post'),
    path('create-page/', views.create_page, name='create-page'),
    path('update_page/<int:page_id>/', views.update_page, name='update_page'),
    path('delete_page/<int:page_id>/', views.delete_page, name='delete_page'),
    path('page/<int:page_id>/create-posts/', views.create_page_post, name='create_page_post'),
    path('follow/<int:page_id>/', views.follow_page, name='follow-page'),
    path('update_page_post/<int:page_id>/', views.update_page_post, name='update_page_post'),
    path('delete_page_post/<int:page_id>/', views.delete_page_post, name='delete_page_post'),
    # path('block-user/', views.block_user, name='block_user'),
    # path('unblock/<str:username>/', views.unblock_user, name='unblock-user'),
    path('block_user/<int:user_id>/', views.block_user, name='block_user'),
    path('list_pages/', views.list_pages, name='list_pages'),
    
    path("core/inbox/", views.inbox, name="inbox"),
    path("core/inbox/<username>/", views.inbox_detail, name="inbox_detail"),
    path('search/', views.search_users, name='search_users'),


    # Group CHat
    path("core/group-inbox/", views.group_inbox, name="group_inbox"),
    path("core/group-inbox/<slug:slug>/", views.group_inbox_detail, name="group_inbox_detail"),
    path("create-group-inbox/", views.create_group_inbox, name="create-group-inbox"),

    # Join & leave Group
    path("core/join-group-page/<slug:slug>/", views.join_group_chat_page, name="join_group_chat_page"),
    path("core/join-group/<slug:slug>/", views.join_group_chat, name="join_group"),
    path("core/leave-group/<slug:slug>/", views.leave_group_chat, name="leave_group_chat"),

    path('forgot_password/', ForgotPasswordView.as_view(), name='forgot_password'),
]

CDPython/social_media-main/social_media-main/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from core.routing import websocket_urlpatterns
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),

    path("ws/", include(websocket_urlpatterns)),

    path('user/change-password/',auth_views.PasswordChangeView.as_view(template_name='userauths/password-reset/change-password.html',success_url = '/user/password-reset-complete/'),name='change_password'),
    path('user/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='userauths/password-reset/password_reset_complete.html'), name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CDPython/social_media-main/social_media-main/userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.RegisterView, name="sign-up"),
    path("sign-in/", views.loginView, name="sign-in"),
    path("sign-out/", views.LogoutView, name="sign-out"),

    path("my-profile/", views.My_Profile, name="my-profile"),
    path("profile/<username>", views.Friend_Profile, name="profile"),
    path("profile-update/", views.profile_update, name="profile-update"),
    
]

CDPython/social_media-main/social_media-main/userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from PIL import Image
from shortuuid.django_fields import ShortUUIDField
from django.utils.html import mark_safe
from django.utils.text import slugify
import shortuuid
from django.db.models.signals import post_save

# Create your models here.

GENDER = (
    ("male","Male"),
    ("female","Female")
)

RELATIONSHIP = (
    ("single", "Single"),
    ("married", "Married")
)

WHO_CAN_SEE_MY_FRIENDS = (
    ("Only Me","Only Me"),
    ("Everyone","Everyone"),
)


def user_directory_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (instance.user.id, ext)
    return 'user_{0}/{1}'.format(instance.user.id,  filename)

class User(AbstractUser):
    full_name = models.CharField(max_length=200)
    username = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=200)
    gender = models.CharField(max_length=100, choices=GENDER, default="male")

    otp = models.CharField(max_length=10, null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return str(self.username)
    
class Profile(models.Model):
    pid = ShortUUIDField(length=7, max_length=25, alphabet="abcdefghijklmnopqrstuvxyz123")
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    cover_image = models.ImageField(upload_to=user_directory_path, default="cover.jpg", blank=True, null=True)
    image = models.ImageField(upload_to=user_directory_path, default="default.jpg", null=True, blank=True)
    full_name = models.CharField(max_length=1000, null=True, blank=True)
    bio = models.CharField(max_length=100, null=True, blank=True)
    about_me = models.CharField( max_length=1000,null=True, blank=True)
    phone = models.CharField(max_length=100, null=True, blank=True)
    gender = models.CharField(max_length=100, choices=GENDER, null=True, blank=True)
    relationship = models.CharField(max_length=100, choices=RELATIONSHIP, null=True, blank=True, default="single")
    friends_visibility = models.CharField(max_length=100, choices=WHO_CAN_SEE_MY_FRIENDS, null=True, blank=True, default="Everyone")
    country = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=100, null=True, blank=True)
    state = models.CharField(max_length=100, null=True, blank=True)
    address = models.CharField(max_length=1000, null=True, blank=True)
    working_at = models.CharField(max_length=1000, null=True, blank=True)
    instagram = models.URLField(default="https://instagram.com/", null=True, blank=True)
    whatsApp = models.CharField(default="+123 (456) 789", max_length=100, blank=True, null=True)
    verified = models.BooleanField(default=False)
    followers = models.ManyToManyField(User, blank=True, related_name="followers")
    followings = models.ManyToManyField(User, blank=True, related_name="followings")
    friends = models.ManyToManyField(User, blank=True, related_name="friends")
    groups = models.ManyToManyField("core.Group", blank=True, related_name="groups")
    pages = models.ManyToManyField("core.Page", blank=True, related_name="pages")
    blocked = models.ManyToManyField(User, blank=True, related_name="blocked")
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    class Meta:
        ordering = ["-date"]

    def __str__(self):
        if self.full_name:
            return str(self.full_name)
        else:
            return str(self.user.username)


    # def save(self, *args, **kwargs):
    #     if self.image:
    #         img = Image.open(self.image.path)
    #         if img.height > 700 or img.width > 700:
    #             output_size = (700, 700)
    #             img.thumbnail(output_size)
    #             img.save(self.image.path)
    #     super().save(*args, **kwargs)

    
    def thumbnail(self):
        return mark_safe('<img src="/media/%s" width="50" height="50" object-fit:"cover" style="border-radius: 30px;" />' % (self.image))



def create_user_profile(sender, instance, created, **kwargs):
	if created:
		Profile.objects.create(user=instance)

def save_user_profile(sender, instance, **kwargs):
	instance.profile.save()


post_save.connect(create_user_profile, sender=User)
post_save.connect(save_user_profile, sender=User)

CDPython/social_media-main/social_media-main/userauths/views.py
from django.shortcuts import render, redirect
from userauths.forms import UserRegisterForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .models import Profile, User
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from core.models import Post, FriendRequest, Group, Page, Block
from userauths.forms import UserRegisterForm, ProfileUpdateForm, UserUpdateForm
from django.http import JsonResponse
# Create your views here.

def RegisterView(request):
    if request.user.is_authenticated:
        messages.warning(request, "You are registered")
        return redirect("core:feed")
    
    form = UserRegisterForm(request.POST or None)
    if form.is_valid():
        form.save()

        full_name = form.cleaned_data.get("full_name")
        phone = form.cleaned_data.get("phone")
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password1")

        user = authenticate(email=email, password=password)
        login(request, user)

        profile = Profile.objects.get(user=request.user)
        profile.full_name = full_name
        profile.phone = phone
        profile.save()

        messages.success(request,f"Hi {full_name}. your account was created successfully.")
        return redirect("core:feed")
    
    context = {
        "form":form
    }
    return render(request, "userauths/sign-up.html", context)

def loginView(request):
    if request.user.is_authenticated:
        messages.warning(request, "You are already login")
        return redirect("core:feed")
    
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")

        try:
            user = User.objects.get(email=email)
            user = authenticate(request, email=email, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, "You are logged in")
                return redirect("core:feed")
            else:
                messages.error(request, "Username or password does not exist")
                return redirect("userauths:sign-up")
        except:
            messages.error(request, "User does not exist")
            return redirect("userauths:sign-up")

    return HttpResponseRedirect("/")

def LogoutView(request):
    logout(request)
    messages.success(request, "You are logged out")
    return redirect("userauths:sign-up")


@login_required
def My_Profile(request):
    profile = request.user.profile
    all_profiles = Profile.objects.all()
    posts = Post.objects.filter(active=True, user=request.user).order_by("-id")
    groups = Group.objects.filter(member=request.user)
    pages = Page.objects.filter(user=request.user)
    user_block = Block.objects.filter(blocker=request.user).exists()
    is_blocked = Block.objects.filter(blocked_user=request.user).exists()
        # Kiểm tra xem người dùng hiện tại có bị chặn bởi profile_user không
    user_block_list = Block.objects.filter(blocker = request.user)
    context = {
        "profile": profile,
        "profiles": all_profiles,
        "posts": posts,
        "groups": groups,
        "pages": pages,
        "user_block":user_block,
        "is_blocked":is_blocked,
        "user_block_list":user_block_list,
    }

    return render(request, "userauths/my-profile.html", context)


@login_required
def Friend_Profile(request, username):
    profile = Profile.objects.get(user__username=username)
    if request.user.profile == profile:
        return redirect("userauths:my-profile")
    posts = Post.objects.filter(active=True, user=profile.user).order_by("-id")
    user_block = Block.objects.filter(blocker=request.user).exists()
    is_blocked = Block.objects.filter(blocked_user=request.user).exists()
        # Kiểm tra xem người dùng hiện tại có bị chặn bởi profile_user không
    user_block_list = Block.objects.filter(blocker = request.user)
    bool = False
    bool_friend = False

    sender = request.user
    receiver = profile.user

    try:
        friend_request = FriendRequest.objects.get(sender=sender, receiver=receiver)
        if friend_request:
            bool = True
        else:
            bool = False
    except:
        bool = False

    context = {
        "posts":posts,
        "bool_friend":bool_friend,
        "bool":bool,
        "profile":profile,
        "user_block":user_block,
        "is_blocked":is_blocked,
        "user_block_list":user_block_list,
    }

    return render(request, "userauths/friend-profile.html", context)


def profile_update(request):
    if request.method == "POST":
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
       

        if p_form.is_valid():
            p_form.save()
            
            messages.success(request, "Profile Updated Successfully.")
            return redirect('userauths:profile-update')
    else:
        p_form = ProfileUpdateForm(instance=request.user.profile)
        

    context = {
        'p_form': p_form,
        
    }
    return render(request, 'userauths/profile-update.html', context)

CDPython/social_media-main/social_media-main/templates/userauths/forgot_password.html
{% block user %}
<div class="login-area">
  <div class="wrapper text-center">
    <div class="title text-uppercase text-center">Quên mật khẩu</div>
    <hr>
    <form class="form-login d-flex flex-column justify-content-center align-items-center" method="post">
      {% csrf_token %}
      <input type="text" name="email" autofocus="" autocapitalize="none" autocomplete="email" maxlength="150" required="" id="id_email" placeholder="Email" {% if email %}disabled{% endif %} value="{{ email|default:'' }}">
      {% if check_email == False %}
      <span class="check-invalid">Email không tồn tại</span>
      {% endif %}
      <div class="otp-area">
        <input type="text" name="otp" maxlength="6" id="id_otp" placeholder="Mã OTP" style="min-width: 250px;" value="{{ otp|default:'' }}">
        <button type="submit" name="send-otp" class="btn-login" style="min-width: 140px;">Gửi mã OTP</button>
      </div>
      {% if check_otp == False %}
      <span class="check-invalid">Mã OTP không chính xác</span>
      {% endif %}
      {% if newpassword %}
      <div class="new-password">
        <span style="min-width: 140px; display: inline-block;">Mật khẩu mới:</span>
        <input type="text" name="new-password" disabled value="{{ newpassword }}" style="min-width: 250px;">
      </div>
      {% endif %}
      <button type="submit" name="submit-form" class="btn-login">Xác nhận</button>
    </form>
    <hr>
    <a href="{% url 'userauths:sign-in' %}" class="btn-register">Đăng nhập</a>
  </div>
</div>

{% endblock %}

CDPython/social_media-main/social_media-main/templates/userauths/profile-update.html
{% extends 'partials/base.html' %}
{% load static %}
{% load widget_tweaks  %}
{% block content %}

        <style>
            
            #id_image{
                background-color: #270041;
                border-radius: 4px;
                height: 50px;
                width: 100%;
                color: #ffffff;
            }
            #id_image::file-selector-button{
                border: none;
                border-radius: 7px;
                color: 432f9f;
                background-color: #ffffff;
                height: 30px;
                cursor: pointer;
                transition: all .25s ease-in;
                margin-top: 1px;
                margin-left: 10px;
            }
        </style>


        <!-- Main Contents -->
        <div class="main_content">
            <div class="mcontainer">

                <div class="bg-white lg:divide-x lg:flex lg:shadow-md rounded-md shadow lg:rounded-xl overflow-hidden lg:m-0 -mx-4">
                    
                    {% include 'partials/settings_sidebar.html' %}
                    <div class="lg:w-2/3">

                        

                        <form method="POST" class="lg:flex lg:flex-col justify-between lg:h-full" enctype="multipart/form-data">
                            {% csrf_token %}
                            <!-- form header -->
                            <div class="lg:px-10 lg:py-8 p-6">
                                <h3 class="font-bold mb-2 text-xl">Profile</h3>
                                <p class=""> This information will be dispalyed publicly so be carful what you share. </p>
                            </div>

                            <!-- form body -->
                            <div class="lg:py-8 lg:px-20 flex-1 space-y-4 p-6">

                                

                                <h4><b>Personal</b></h4>
                                <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                                    <!-- Column 1: Profile Image -->
                                    <div class="bg-gray-100 p-4  flex items-center" style="border-radius: 10px;">
                                        <div class="relative">
                                            <img src="{{request.user.profile.image.url}}" id="preview_avatar" alt="Profile Picture" class="w-24 h-24 rounded-full">
                                            <label for="id_image" class="absolute bottom-0 right-0 p-2 bg-white rounded-full cursor-pointer">
                                                <i class="fas fa-pen text-blue-500"></i>
                                            </label>
                                        </div>
                                    </div>


                                    <!-- Column 2: Cover Image -->
                                    <div class="bg-blue-100 p-4" style="border-radius: 10px;">
                                        <div class="relative">
                                        <img src="{{request.user.profile.cover_image.url}}" id="preview_cover" alt="Cover Image" class="w-full h-32 object-cover rounded-lg">
                                        <label for="id_cover_image" class="absolute bottom-0 right-0 p-2 bg-white rounded-full cursor-pointer">
                                            <i class="fas fa-pen text-blue-500"></i>
                                        </label>
                                        </div>
                                    </div>

                                    <script>
                                        var loadFile = function (event) {
                                          var output1 = document.getElementById("preview_avatar");
                                          output1.src = URL.createObjectURL(event.target.files[0]);
                                          output1.onload = function () {
                                            URL.revokeObjectURL(output1.src); // free memory
                                          };
                                        };

                                        var loadFile2 = function (event) {
                                          var output2 = document.getElementById("preview_cover");
                                          output2.src = URL.createObjectURL(event.target.files[0]);
                                          output2.onload = function () {
                                            URL.revokeObjectURL(output2.src); // free memory
                                          };
                                        };
                                      </script>

                                </div>
                                <div class="d-none">
                                    <div class="line">
                                        {% render_field p_form.image onchange="loadFile(event)" class="hidden"  %}
                                    </div>
                                    <div class="line">
                                        {% render_field p_form.cover_image onchange="loadFile2(event)" class="hidden"  %}
                                    </div>
                                </div>
                                <div class="line">
                                    {% render_field p_form.full_name class="line__input" %}
                                    <span for="username" class="line__placeholder"> First Name   </span>
                                </div>
                                <div class="line">
                                    {% render_field p_form.bio class="line__input"  %}
                                    <span for="username" class="line__placeholder"> Bio  </span>
                                </div>
                                <div class="line">
                                    {% render_field p_form.about_me class="line__input" %}
                                    <span for="username" class="line__placeholder"> About Me   </span>
                                </div>
                                <div class="line">
                                    {% render_field p_form.relationship class="line__input" %}
                                    <span for="username" class="line__placeholder"> Relationship Status   </span>
                                </div>
                            </div>

                            <div class="lg:py-4 lg:px-20 flex-1 space-y-4 p-6">
                                <h4><b>Contact</b></h4>
                                <div class="line">
                                    {% render_field p_form.phone class="line__input" %}
                                    <span for="username" class="line__placeholder"> Mobile Number   </span>
                                </div>
                                
                            </div>

                            <div class="lg:py-4 lg:px-20 flex-1 space-y-4 p-6">
                                <h4><b>Address</b></h4>
                                <div class="line">
                                    {% render_field p_form.address class="line__input" %}
                                    <span for="username" class="line__placeholder"> Address   </span>
                                </div>
                                <div class="line">
                                    {% render_field p_form.city class="line__input" %}
                                    <span for="username" class="line__placeholder"> City  </span>
                                </div>
                                <div class="line">
                                    {% render_field p_form.state class="line__input" %}
                                    <span for="username" class="line__placeholder"> State  </span>
                                </div>
                                <div class="line">
                                    {% render_field p_form.country class="line__input" %}
                                    <span for="username" class="line__placeholder"> State  </span>
                                </div>
                            </div>

                            <div class="lg:py-4 lg:px-20 flex-1 space-y-4 p-6">
                                <h4><b>Address</b></h4>
                                <div class="line">
                                    {% render_field p_form.address class="line__input" %}
                                    <span for="username" class="line__placeholder"> Address   </span>
                                </div>
                                <div class="line">
                                    {% render_field p_form.city class="line__input" %}
                                    <span for="username" class="line__placeholder"> City  </span>
                                </div>
                                <div class="line">
                                    {% render_field p_form.state class="line__input" %}
                                    <span for="username" class="line__placeholder"> State  </span>
                                </div>
                                <div class="line">
                                    {% render_field p_form.country class="line__input" %}
                                    <span for="username" class="line__placeholder"> State  </span>
                                </div>
                            </div>

                            <div class="lg:py-4 lg:px-20 flex-1 space-y-4 p-6">
                                <h4><b>Socila URLs</b></h4>
                                <div class="line">
                                    {% render_field p_form.instagram class="line__input" %}
                                    <span for="username" class="line__placeholder"> Instagram   </span>
                                </div>
                                <div class="line">
                                    {% render_field p_form.whatsApp class="line__input" %}
                                    <span for="username" class="line__placeholder"> WhatsApp  </span>
                                </div>
                            </div>

                            <div class="bg-gray-10 p-6 pt-0 flex justify-end space-x-3">
                                <button type="submit" class="button bg-blue-700"> Save Changes </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

{% endblock content %}