CDPython/social_media-main/social_media-main/core/urls.py
from django.urls import path
from core.views import index, JoinGroupView, LeaveGroupView, ManageGroupMembershipView,ListPendingMembershipsView, ConfirmMembershipView, delete_post, ForgotPasswordView
from core import views

app_name = "core"

urlpatterns = [
    path("",index, name="feed"),
    path("post/<slug:slug>/", views.post_detail, name="post-detail"),

    path("create-post/", views.create_post, name="create-post"),
    path("like-post/", views.like_post, name="like-post"),
    path("comment-post/", views.comment_on_post, name="comment-post"),
    path("like-comment/", views.like_comment, name="like-comment"),
    path("reply-comment/", views.reply_comment, name="reply-comment"),
    path("delete-comment/", views.delete_comment, name="delete-comment"),
    path('delete_post/', views.delete_post, name='delete_post'),
    path("add-friend/", views.add_friend, name="add-friend"),
    path("accept-friend-request/", views.accept_friend_request, name="accept-friend-request"),
    path("reject-friend-request/", views.reject_friend_request, name="reject-friend-request"),
    path("unfriend/", views.unfriend, name="unfriend"),
    path('delete-reply/', views.delete_reply, name='delete-reply'),
    path("like-page/", views.like_page, name="like-page"),
    path('edit-comment/', views.edit_comment, name='edit_comment'),
    path('delete_post/<slug:slug>/', views.delete_post, name='delete_post'),
    path('update_post/<slug:slug>/', views.update_post, name='update_post'),
    path('edit-reply/', views.edit_reply, name='edit_reply'),
    path('unblock_user/<int:user_id>/', views.unblock_user, name='unblock_user'),

    path('group/<int:group_id>/post-list/', views.group_post_list, name='group_post_list'),
    path('group/<int:group_id>/create-post/', views.create_group_post, name='create_group_post'),
    path('create-group/', views.create_group, name='create-group'),
    path("group-page/<id>/",views.group_index, name="group-page"),
    path('join-group/<int:group_id>/', JoinGroupView.as_view(), name='join-group'),
    path('leave-group/<int:group_id>/', LeaveGroupView.as_view(), name='leave-group'),
    path('manage-membership/<int:group_id>/<int:user_id>/<str:action>/', ManageGroupMembershipView.as_view(), name='manage-membership'),
    path('pending-memberships/<int:group_id>/', ListPendingMembershipsView.as_view(), name='pending-memberships'),
    path('confirm-membership/<int:user_id>/<str:action>/<int:group_id>/', ConfirmMembershipView.as_view(), name='confirm-membership'),
    path('delete_group/<int:group_id>/', views.delete_group, name='delete_group'),
    path('update_group/<int:group_id>/', views.update_group, name='update_group'),
    path('follow_user/<str:username>/', views.follow_user, name='follow_user'),
    path('groups/<int:group_id>/leave/', LeaveGroupView.as_view(), name='leave-group'),
    path('update_group_post/<int:group_id>/', views.update_group_post, name='update_group_post'),
    path('delete_group_post/<int:group_id>/', views.delete_group_post, name='delete_group_post'),
    path('list_groups/', views.list_groups, name='list_groups'),
     path('list_non_friends/', views.list_non_friends, name='list_non_friends'),

    path('page/<int:page_id>/post-list/', views.page_post_list, name='page_post_list'),
    #path('page/<int:page_id>/create-post/', views.create_page_post, name='create_page_post'),
    path('create-page/', views.create_page, name='create-page'),
    path('update_page/<int:page_id>/', views.update_page, name='update_page'),
    path('delete_page/<int:page_id>/', views.delete_page, name='delete_page'),
    path('page/<int:page_id>/create-posts/', views.create_page_post, name='create_page_post'),
    path('follow/<int:page_id>/', views.follow_page, name='follow-page'),
    path('update_page_post/<int:page_id>/', views.update_page_post, name='update_page_post'),
    path('delete_page_post/<int:page_id>/', views.delete_page_post, name='delete_page_post'),
    # path('block-user/', views.block_user, name='block_user'),
    # path('unblock/<str:username>/', views.unblock_user, name='unblock-user'),
    path('block_user/<int:user_id>/', views.block_user, name='block_user'),
    path('list_pages/', views.list_pages, name='list_pages'),
    
    path("core/inbox/", views.inbox, name="inbox"),
    path("core/inbox/<username>/", views.inbox_detail, name="inbox_detail"),
    path('search/', views.search_users, name='search_users'),


    # Group CHat
    path("core/group-inbox/", views.group_inbox, name="group_inbox"),
    path("core/group-inbox/<slug:slug>/", views.group_inbox_detail, name="group_inbox_detail"),
    path("create-group-inbox/", views.create_group_inbox, name="create-group-inbox"),

    # Join & leave Group
    path("core/join-group-page/<slug:slug>/", views.join_group_chat_page, name="join_group_chat_page"),
    path("core/join-group/<slug:slug>/", views.join_group_chat, name="join_group"),
    path("core/leave-group/<slug:slug>/", views.leave_group_chat, name="leave_group_chat"),

    path('forgot_password/', ForgotPasswordView.as_view(), name='forgot_password'),
]

CDPython/social_media-main/social_media-main/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from core.routing import websocket_urlpatterns
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),

    path("ws/", include(websocket_urlpatterns)),

    path('user/change-password/',auth_views.PasswordChangeView.as_view(template_name='userauths/password-reset/change-password.html',success_url = '/user/password-reset-complete/'),name='change_password'),
    path('user/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='userauths/password-reset/password_reset_complete.html'), name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CDPython/social_media-main/social_media-main/core/models.py
from django.db import models
from userauths.models import User, Profile, user_directory_path
from shortuuid.django_fields import ShortUUIDField
from django.utils.text import slugify
import shortuuid
from django.utils.html import mark_safe




# Create your models here.

VISIBILITY = (
    ("Only Me", "Only Me"),
    ("Everyone", "Everyone"),
)

FRIEND_REQUEST = (
    ("pending","pending"),
    ("accept","Accept"),
    ("reject","Reject"),
)

NOTIFICATION_TYPE = (
    ("Friend Request", "Friend Request"),
    ("Friend Request Accepted", "Friend Request Accepted"),
    ("New Follower", "New Follower"),
    ("New Like", "New Like"),
    ("New Comment", "New Comment"),
    ("Comment Liked", "Comment Liked"),
    ("Comment Replied", "Comment Replied"),
)

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=500, blank=True, null=True)
    image = models.ImageField(upload_to=user_directory_path, blank=True, null=True)
    video = models.FileField(upload_to=user_directory_path, blank=True, null=True)
    visibility = models.CharField(max_length=100, choices=VISIBILITY, default="Everyone")
    pid = ShortUUIDField(length=7, max_length=25, alphabet='abcdefghijklmnopqrstuvwxyz')
    likes = models.ManyToManyField(User, blank=True, related_name="likes")
    active = models.BooleanField(default=True)
    slug = models.SlugField(unique=True)
    views = models.PositiveIntegerField(default=0)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ["-date"]
        verbose_name_plural = "Post"
    
    def save(self, *args, **kwargs):
        uuid_key = shortuuid.uuid()
        uniqueid = uuid_key[:4]
        if self.slug == "" or self.slug == None:
            self.slug = slugify(self.title) + "-" + str(uniqueid.lower())
        super(Post, self).save(*args, **kwargs) 

    def thumbnail(self):
        return mark_safe('<img src="/media/%s" width="50" height="50" object-fit:"cover" style="border-radius: 5px;" />' % (self.image))
    
    def gallery_images(self):
        return Gallery.objects.filter(post=self)
    
    def title_len_count(self):
        return len(self.title)
    
    def galley_img_count(self):
        return Gallery.objects.filter(post=self).count()

    def post_comments(self):
        comments = Comment.objects.filter(post=self, active=True)
        return comments
    
    def post_comments_count(self):
        comments_count = Comment.objects.filter(post=self, active=True).count()
        return comments_count
    

class Gallery(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="gallery", null=True, blank=True)
    active = models.BooleanField(default=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.post)
    
    class Meta:
        verbose_name_plural = 'Gallery'

    def thumbnail(self):
        return mark_safe('<img src="/media/%s" width="50" height="50" object-fit:"cover" style="border-radius: 5px;" />' % (self.image))

class FriendRequest(models.Model):
    fid = ShortUUIDField(length=7, max_length=25, alphabet='abcdefghijklmnopqrstuvwxyz')
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="request_sender")
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name="request_receiver")
    status = models.CharField(max_length=100, default="pending", choices=FRIEND_REQUEST)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.sender)
    
    class Meta:
        verbose_name_plural = 'Friend Request'

class Block(models.Model):
    blocker = models.ForeignKey(User, related_name='blocker', on_delete=models.CASCADE)
    blocked_user = models.ForeignKey(User, related_name='blocked_user', on_delete=models.CASCADE)

    class Meta:
        unique_together = ('blocker', 'blocked_user')
    
    

class Friend(models.Model):
    fid = ShortUUIDField(length=7, max_length=25, alphabet='abcdefghijklmnopqrstuvwxyz')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user")
    friend = models.ForeignKey(User, on_delete=models.CASCADE, related_name="friend")

    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user)
    
    class Meta:
        verbose_name_plural = 'Friend'

class Comment(models.Model):
    cid = ShortUUIDField(length=7, max_length=25, alphabet='abcdefghijklmnopqrstuvwxyz')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="commnet_user")
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)
    date = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, blank=True, related_name="commnet_likes")
    comment = models.CharField(max_length=1000)

    def __str__(self):
        return str(self.post)
    
    class Meta:
        verbose_name_plural = 'Comment'

    def comment_replies(self):
        comment_replies = ReplyComment.objects.filter(comment=self, active=True)
        return comment_replies

class ReplyComment(models.Model):
    cid = ShortUUIDField(length=7, max_length=25, alphabet='abcdefghijklmnopqrstuvwxyz')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="reply_user")
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)
    date = models.DateTimeField(auto_now_add=True)
    reply = models.CharField(max_length=1000)

    def __str__(self):
        return str(self.comment)
    
    class Meta:
        verbose_name_plural = 'Reply Comment'

class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="noti_user")
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="noti_sender")
    post = models.ForeignKey(Post, on_delete=models.SET_NULL, null=True, blank=True)
    comment = models.ForeignKey(Comment, on_delete=models.SET_NULL, null=True, blank=True)
    notification_type = models.CharField(max_length=500, choices=NOTIFICATION_TYPE)
    is_read = models.BooleanField(default=False)
    nid = ShortUUIDField(length=7, max_length=25, alphabet='abcdefghijklmnopqrstuvwxyz')
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user)
    
    class Meta:
        verbose_name_plural = 'Notification'

class Group(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="group")
    member = models.ManyToManyField(User, blank=True, related_name="members")

    description = models.TextField(max_length=500, blank=True, null=True)
    name = models.CharField(max_length=500, blank=True, null=True)
    image = models.ImageField(upload_to=user_directory_path, blank=True, null=True,default="cover.jpg")
    image2 = models.ImageField(upload_to=user_directory_path, blank=True, null=True,default="cover.jpg")
    visibility = models.CharField(max_length=100, choices=VISIBILITY, default="Everyone")
    gid = ShortUUIDField(length=7, max_length=25, alphabet='abcdefghijklmnopqrstuvwxyz')
    active = models.BooleanField(default=True)
    slug = models.SlugField(unique=True)
    views = models.PositiveIntegerField(default=0)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        if self.name:
            return self.name
        else:
            return self.user.username
        
    def save(self, *args, **kwargs):
        uuid_key = shortuuid.uuid()
        uniqueid = uuid_key[:2]
        if self.slug == "" or self.slug == None:
            self.slug = slugify(self.name) + '-' + uniqueid

        super(Group, self).save(*args, **kwargs)
    
    def thumbnail(self):
        return mark_safe('<img src="/media/%s" width="50" height="50" object-fit:"cover" style="border-radius: 5px;" />' % (self.image))

class GroupPost(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=500, blank=True, null=True)
    image = models.ImageField(upload_to=user_directory_path, blank=True, null=True)
    video = models.FileField(upload_to=user_directory_path, blank=True, null=True)
    visibility = models.CharField(max_length=100, choices=VISIBILITY, default="Everyone")
    pid = ShortUUIDField(length=7, max_length=25, alphabet='abcdefghijklmnopqrstuvwxyz')
    likes = models.ManyToManyField(User, blank=True, related_name="group_post_likes")
    active = models.BooleanField(default=True)
    slug = models.SlugField(unique=True)
    views = models.PositiveIntegerField(default=0)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        if self.title:
            return self.title
        else:
            return self.user.username
        
    def save(self, *args, **kwargs):
        uuid_key = shortuuid.uuid()
        uniqueid = uuid_key[:4]
        if self.slug == "" or self.slug == None:
            self.slug = slugify(self.title) + "-" + str(uniqueid.lower())
        super(GroupPost, self).save(*args, **kwargs) 
    
    def thumbnail(self):
        return mark_safe('<img src="/media/%s" width="50" height="50" object-fit:"cover" style="border-radius: 5px;" />' % (self.image))


class Page(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="page_user")
    follower = models.ManyToManyField(User, related_name="page_menber")
    likes = models.ManyToManyField(User, blank=True, related_name="page_likes")
    description = models.TextField(max_length=500, blank=True, null=True)
    name = models.CharField(max_length=500, blank=True, null=True)
    image = models.ImageField(upload_to=user_directory_path, blank=True, null=True)

CDPython/social_media-main/social_media-main/templates/core/confirm_block_user.html
{% block content %}
  <h2>Block User</h2>
  <p>Are you sure you want to block {{ blocked_user.username}}?</p>

  <form method="post" action="{% url 'core:block_user' blocked_user.id %}">
    {% csrf_token %}
    <button type="submit">Block User</button>
  </form>

  {% comment %} <a href="{% url 'profiles:profile' pk=blocked_user.id %}">Cancel</a> {% endcomment %}
{% endblock %}

CDPython/social_media-main/social_media-main/templates/core/confirm_delete_group.html
{% extends 'partials/base.html' %}
{% load static %}
{% load widget_tweaks  %}
{% block content %}

<style>
    .confirmation-container {
        max-width: 600px; /* Adjust the max-width as needed */
        margin: auto;
        padding: 20px;
        background-color: #fff;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        border-radius: 8px;
    }

    .confirmation-container h2 {
        font-size: 1.5rem;
        margin-bottom: 15px;
        color: #333;
    }

    .confirmation-container p {
        font-size: 1rem;
        margin-bottom: 20px;
        color: #555;
    }

    .confirmation-container form {
        display: inline-block;
        margin-right: 10px;
    }

    .confirmation-container input[type="submit"] {
        background-color: #e53e3e; /* Red color, you can change it */
        color: #fff;
        padding: 10px 15px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }

    .confirmation-container a {
        color: #3490dc; /* Blue color, you can change it */
        text-decoration: none;
        cursor: pointer;
    }

    .confirmation-container a:hover {
        text-decoration: underline;
    }

    #id_image{
        background-color: #270041;
        border-radius: 4px;
        height: 50px;
        width: 100%;
        color: #ffffff;
    }
    #id_image::file-selector-button{
        border: none;
        border-radius: 7px;
        color: 432f9f;
        background-color: #ffffff;
        height: 30px;
        cursor: pointer;
        transition: all .25s ease-in;
        margin-top: 1px;
        margin-left: 10px;
    }
</style>


        <!-- Main Contents -->
        <div class="main_content">
            <div class="mcontainer">

                <div class="bg-white lg:divide-x lg:flex lg:shadow-md rounded-md shadow lg:rounded-xl overflow-hidden lg:m-0 -mx-4">
                    
                    {% include 'partials/group_sidebar.html' %}
                    <div class="lg:w-2/3 confirmation-container">
                        <h2>Confirm Delete</h2>
                        <p>Are you sure you want to delete the page "{{ group.name }}"?</p>

                      <form method="post" action="{% url 'core:delete_group' group.id %}">
                        {% csrf_token %}
                        <input type="submit" value="Delete">
                      </form>

                      <a href="{% url 'core:feed'%}">Cancel</a>  <!-- Replace 'profile' with the URL name of the user's profile -->
                                            

                        
                    </div>
                </div>
            </div>
        </div>

{% endblock content %}

CDPython/social_media-main/social_media-main/templates/core/confirm_delete_page.html
{% extends 'partials/base.html' %}
{% load static %}
{% load widget_tweaks  %}
{% block content %}

<style>
    .confirmation-container {
        max-width: 600px; /* Adjust the max-width as needed */
        margin: auto;
        padding: 20px;
        background-color: #fff;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        border-radius: 8px;
    }

    .confirmation-container h2 {
        font-size: 1.5rem;
        margin-bottom: 15px;
        color: #333;
    }

    .confirmation-container p {
        font-size: 1rem;
        margin-bottom: 20px;
        color: #555;
    }

    .confirmation-container form {
        display: inline-block;
        margin-right: 10px;
    }

    .confirmation-container input[type="submit"] {
        background-color: #e53e3e; /* Red color, you can change it */
        color: #fff;
        padding: 10px 15px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }

    .confirmation-container a {
        color: #3490dc; /* Blue color, you can change it */
        text-decoration: none;
        cursor: pointer;
    }

    .confirmation-container a:hover {
        text-decoration: underline;
    }

    #id_image{
        background-color: #270041;
        border-radius: 4px;
        height: 50px;
        width: 100%;
        color: #ffffff;
    }
    #id_image::file-selector-button{
        border: none;
        border-radius: 7px;
        color: 432f9f;
        background-color: #ffffff;
        height: 30px;
        cursor: pointer;
        transition: all .25s ease-in;
        margin-top: 1px;
        margin-left: 10px;
    }
</style>


        <!-- Main Contents -->
        <div class="main_content">
            <div class="mcontainer">

                <div class="bg-white lg:divide-x lg:flex lg:shadow-md rounded-md shadow lg:rounded-xl overflow-hidden lg:m-0 -mx-4">
                    
                    {% include 'partials/update_sidebar.html' %}
                    <div class="lg:w-2/3 confirmation-container">
                        <h2>Confirm Delete</h2>
                        <p>Are you sure you want to delete the page "{{ page.name }}"?</p>
                        <form method="post" action="{% url 'core:delete_page' page.id %}">
                        {% csrf_token %}
                        <input type="submit" value="Delete">
                        </form>
                        <a href="{% url 'core:feed' %}">Cancel</a>
                        </div>
                </div>
            </div>
        </div>

{% endblock content %}

CDPython/social_media-main/social_media-main/templates/core/delete_group_post.html
{% extends 'partials/base.html' %}
{% load static %}
{% load widget_tweaks  %}
{% block content %}

<style>
    body {
        font-family: 'Arial', sans-serif;
        background-color: #f5f5f5;
    }

    .confirmation-container {
        max-width: 600px;
        margin: 75px auto;
        padding: 20px;
        background-color: #fff;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        border-radius: 8px;
    }

    h2 {
        font-size: 1.8rem;
        color: #333;
    }

    p {
        font-size: 1.2rem;
        color: #555;
        margin-bottom: 20px;
    }

    form {
        display: inline-block;
        margin-right: 10px;
    }

    input[type="submit"] {
        background-color: #e53e3e; /* Red color, you can change it */
        color: #fff;
        padding: 10px 15px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }

    a {
        color: #3490dc; /* Blue color, you can change it */
        text-decoration: none;
        cursor: pointer;
    }

    a:hover {
        text-decoration: underline;
    }
</style>

<div class="confirmation-container">
    <h2>Confirm Delete</h2>
    <p>Are you sure you want to delete the post "{{ group_post.title }}"?</p>
    <form method="post" action="{% url 'core:delete_group_post' group_post.group.id %}">
        {% csrf_token %}
        <input type="submit" value="Delete">
    </form>
    <a href="{% url 'core:feed' %}">Cancel</a>
</div>

{% endblock %}

CDPython/social_media-main/social_media-main/templates/core/group-page.html
{{posts}}

CDPython/social_media-main/social_media-main/templates/core/list_pending_memberships.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pending Memberships</title>
</head>
<body>
    <h1>Pending Memberships for {{ group.name }}</h1>

    {% if pending_memberships %}
        <ul>
            {% for membership in pending_memberships %}
                <li>
                    <p>User: {{ membership.user.username }}</p>
                    <p>Status: {{ membership.status }}</p>
                    <button class="accept">
                        {% comment %} <a href="{% url 'confirm-membership' user.id 'approve' group.id  %}" class="accept-link">Xác nhận</a> {% endcomment %}
                    </button>
                    <button class="reject">
                        {% comment %} <a href="{% url 'confirm-membership' message.user.id 'reject' message.group.id %}" class="reject-link">Từ chối</a> {% endcomment %}
                    </button>
                    
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No pending membership requests</p>
    {% endif %}

    <a href="{% url 'core:group_post_list' group_id=group.id %}">Back to Group Post List</a>
</body>
</html>

CDPython/social_media-main/social_media-main/templates/core/update_page.html
{% extends 'partials/base.html' %}
{% load static %}
{% load widget_tweaks  %}
{% block content %}

        <style>
            
            #id_image{
                background-color: #270041;
                border-radius: 4px;
                height: 50px;
                width: 100%;
                color: #ffffff;
            }
            #id_image::file-selector-button{
                border: none;
                border-radius: 7px;
                color: 432f9f;
                background-color: #ffffff;
                height: 30px;
                cursor: pointer;
                transition: all .25s ease-in;
                margin-top: 1px;
                margin-left: 10px;
            }
        </style>


        <!-- Main Contents -->
        <div class="main_content">
            <div class="mcontainer">

                <div class="bg-white lg:divide-x lg:flex lg:shadow-md rounded-md shadow lg:rounded-xl overflow-hidden lg:m-0 -mx-4">
                    
                    {% include 'partials/update_sidebar.html' %}
                    <div class="lg:w-2/3">

                        

                        <form method="POST" class="lg:flex lg:flex-col justify-between lg:h-full" enctype="multipart/form-data">
                            {% csrf_token %}
                            <!-- form header -->
                            <div class="lg:px-10 lg:py-8 p-6">
                                <h3 class="font-bold mb-2 text-xl">Profile</h3>
                                <p class=""> This information will be dispalyed publicly so be carful what you share. </p>
                            </div>

                            <!-- form body -->
                            <div class="lg:py-8 lg:px-20 flex-1 space-y-4 p-6">

                                

                                <h4><b>Pagel</b></h4>
                                <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                                    <!-- Column 1: Profile Image -->
                                    <div class="bg-gray-100 p-4  flex items-center" style="border-radius: 10px;">
                                        <div class="relative">
                                            <img src="{{page.image.url}}" id="preview_avatar" alt="Profile Picture" class="w-24 h-24 rounded-full">
                                            <label for="id_image" class="absolute bottom-0 right-0 p-2 bg-white rounded-full cursor-pointer">
                                                <i class="fas fa-pen text-blue-500"></i>
                                            </label>
                                        </div>
                                    </div>


                                    <!-- Column 2: Cover Image -->
                                    <div class="bg-blue-100 p-4" style="border-radius: 10px;">
                                        <div class="relative">
                                        <img src="{{page.image_page.url}}" id="preview_cover" alt="Cover Image" class="w-full h-32 object-cover rounded-lg">
                                        <label for="id_cover_image" class="absolute bottom-0 right-0 p-2 bg-white rounded-full cursor-pointer">
                                            <i class="fas fa-pen text-blue-500"></i>
                                        </label>
                                        </div>
                                    </div>

                                    <script>
                                        var loadFile = function (event) {
                                          var output1 = document.getElementById("preview_avatar");
                                          output1.src = URL.createObjectURL(event.target.files[0]);
                                          output1.onload = function () {
                                            URL.revokeObjectURL(output1.src); // free memory
                                          };
                                        };

                                        var loadFile2 = function (event) {
                                          var output2 = document.getElementById("preview_cover");
                                          output2.src = URL.createObjectURL(event.target.files[0]);
                                          output2.onload = function () {
                                            URL.revokeObjectURL(output2.src); // free memory
                                          };
                                        };
                                      </script>

                                </div>
                                <div class="d-none">
                                    <div class="line">
                                        {% render_field form.image onchange="loadFile(event)" class="hidden"  %}
                                    </div>
                                    <div class="line">
                                        {% render_field form.image_page onchange="loadFile2(event)" class="hidden"  %}
                                    </div>
                                </div>
                                <div class="line">
                                    {% render_field form.name class="line__input" %}
                                    <span for="username" class="line__placeholder"> Name   </span>
                                </div>
                                
                                <div class="line">
                                    {% render_field form.description class="line__input" %}
                                    <span for="username" class="line__placeholder"> Description   </span>
                                </div>
                                
                                <div class="line">
                                    {% render_field form.visibility class="line__input"  %}
                                    <span for="username" class="line__placeholder"> visibility  </span>
                                </div>
                            </div>
                                

                            <div class="bg-gray-10 p-6 pt-0 flex justify-end space-x-3">
                                <button type="submit" class="button bg-blue-700"> Save Changes </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

{% endblock content %}